#page title
page_title                                : PrayPal                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://praypal.io                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : PrayPal                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Pray on time, rain or shine

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mohammad Abuosbie
your_link                                 : 
your_city                                 : 
email_address                             : help@praypal.io
facebook_username                         :                                           
instagram_username                        : praypal.io
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Accurate Prayer Times
    description                           : Get precise prayer timings tailored to your location, ensuring you never miss a salah.
    fontawesome_icon_name                 : clock
    
  - title                                 : Real-time Weather
    description                           : Stay informed with up-to-date weather conditions to plan your day and prayers effectively.
    fontawesome_icon_name                 : sun

  - title                                 : Qibla
    description                           : Easily find the direction of the Kaaba wherever you are, with accurate compass guidance.
    fontawesome_icon_name                 : compass



# Theme Settings
topbar_color                              : "#223a5e"
topbar_transparency                       : 0.3
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#223a5e"

link_color                                : "#c39e6d"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#c39e6d"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#c39e6d"
feature_icons_background_color            : "#ffffff"

social_icons_foreground_color             : "#c39e6d"
social_icons_background_color             : "#ffffff"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
